sudo: false
language: python

git:
  depth: 3
  submodules: false

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - python create_db.py

script:
  - python app-test.py

notifications:
  email: false